#!/usr/bin/env bash
#Transfer file from client to server

if [ $# -le 3  ]; then
	echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
	exit
fi
scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":"$4"
