#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html

# redirection
BLOCK="location /redirect_me {return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}"
sudo sed -i "30i $BLOCK" /etc/nginx/sites-enabled/default
sudo systemctl reload nginx
