#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html

BLOCK="location = /redirect_me {https://www.youtube.com/watch?v=QH2-TGUlwu4;}"
sudo sed -i "/server_name/i $BLOCK" /etc/ngix/sites-enabled/default
service nginx start
