#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html

# redirection
BLOCK="location = /redirect_me {https://www.youtube.com/watch?v=QH2-TGUlwu4;}"
sudo sed -i "30i $BLOCK" /etc/ngix/sites-enabled/default
sudo systemctl reload nginx

#Custom error page
CUSTOM="error_page 404 /404.html;\nlocation = /404.html {\nroot /var/www/html;\ninternal;\n}"
sudo sed -i "/server_name _;/a $CUSTOM" /etc/nginx/sites-available/default
service nginx restart
