#!/usr/bin/env bash
#bash script that creates the file /var/run/myscript.pid

terminator () {
	rm '/var/run/myscript.pid'
}


echo "$$" > /var/run/myscript.pid
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill commnad" && terminator' SIGTERM
trap 'terminator; exit' SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
