#!/usr/bin/env bash
#Bash script that loops from 1 to 10

num=1

while [ $num -lt 11 ]
do
	if (( num == 4)) 
	then
		echo "bad luck"
	elif (( num == 8 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	num=$(( num+1 ))
done
