#!/usr/bin/env bash
#Bash script that loops from 1 to 10

num=1

while [ $num -lt 21 ]
do
	case $num in
		5) echo "bad luck from China";;
		10) echo "bad luck from Japan";;
		18) echo "bad luck from Italy";;
	esac
	echo $num
	num=$(( num+1 ))
done
