#!/usr/bin/env bash
#Bash script that loops from 1 to 10

num=1

while [ $num -lt 21 ]
do
	case $num in
		4) echo "bad luck from china";;
		9) echo "bad luck from japan";;
		17) echo "bad luck from italy";;
		*) echo $num;;
	esac
	num=$(( num+1 ))
done
