#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes

hour=0
min=0

while [ $hour -lt 13 ]
do
	echo "Hour: $hour"
	while [ $min -lt 60 ]
	do
		echo $min
		min=$(( min+1 ))
	done
	hour=$(( hour+1 ))
	min=0
done
